### ISSUE TITLE
files under Content Upload folder is not under https

### ISSUE THREAD

**Issue by mafloria** [phikai/wordpress-force-https#3]
Hi,
I'm having issues displaying images and files under the uploads folder. I activate the pluging and all the pages are working under https, but the urls for display the uploaded images and files continues under http. 
What can I do?

Thanks

**Comment by squio** [comment]
Hi, this plugin works on all requests which pass through the Wordpress scripting evaluation. This is not the case for static files, such as your uploaded content. Most likely these files (images) are embedded in your pages with the full URL from before your switch to https. You can fix this by re-editing all your relevant pages and remove the `http://your-site.com` part or change `http` into `https`. Or try some site migration option. Maybe changing your official site address to the full url including https will work (Admin / Settings / General). YMMV!
