### ISSUE TITLE
Does not force homepage to https

### ISSUE THREAD

**Issue by drummerck13** [phikai/wordpress-force-https#8]
Plugin does not initially force user to login over HTTPS. After logging in over HTTP and accessing the main site, the user must attempt to edit profile settings before being forced to login over HTTPS. The option to log in over HTTPS initially is always there. However, it is not forced. This bug is was found on Firefox.

**Comment by phikai** [comment]
The plugin does not force this setting... it's suggested to use these settings:

https://codex.wordpress.org/Administration_Over_SSL
